LOGROOT: /Users/arthur/Travail/flying_foxes_study/AudioEventDetection/DENet/logs
CMD: "python train.py"

HPARAMS: [
  {
   logdir: LOGDIR,
   adam: true,
   arch: denet,
   lr: [0.01, 0.02],
   epochs: 10,
   RUNX.TAG: 'denet',
  },
  {
   arch: denet,
   lr: [0.002, 0.005],
   RUNX.TAG: 'denet_low_lr',
  },
  {
   RUNX.SKIP: true,
   arch: sincnet,
   lr: [0.002, 0.005],
   RUNX.TAG: 'sincnet',
  }
]
